// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCW_dtNs8U8cCSBJffnT3I6ZNNBOwQiRxo',
    appId: '1:972782463143:android:56e5c35619e2c178755382',
    messagingSenderId: '972782463143',
    projectId: 'das-running-app',
    storageBucket: 'das-running-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBalJPjnuLEOLptAg_tU1R236l3ZJkP57s',
    appId: '1:972782463143:ios:255e08805f44cde8755382',
    messagingSenderId: '972782463143',
    projectId: 'das-running-app',
    storageBucket: 'das-running-app.firebasestorage.app',
    androidClientId: '972782463143-6qs0hbegidbtunqa6v68ba5l8f4363pu.apps.googleusercontent.com',
    iosClientId: '972782463143-h2f4isa76ph1q0gha4qhdu32npf5fm4g.apps.googleusercontent.com',
    iosBundleId: 'com.example.dasRunningApp',
  );

}